version: '3'
services: 
  backend: 
    image: utsavjain/titanbackend
    ports:
      - "3050:3050"
    depends_on:
      - dbworker
  dbworker:
    image: utsavjain/titandbworker
    ports:
      - "3000:3000"
    