version: '3'
services: 
  backend: 
    image: utsavjain/titanbackend
    port:
      - "3050:3050"
    depends_on:
      - dbworker
  dbworker:
    image: utsavjain/titandbworker
    port:
      - "3000:3000"
    